<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Accounting_model extends MY_Model
{

    public $table = 'accountings';
    public $id = 'id';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // datatables
    function json($contract_id = NULL) {
        $this->datatables->select('a.id,a.in_out,b.reference_name,a.activity_id,c.activity_name,a.activity_date,format(a.amount,0) as amount ,a.people,a.description,a.status_data,a.create_userid,a.update_userid,a.create_time,a.update_time');
        $this->datatables->from('accountings a');
        $this->datatables->join('ref_accountings b','b.id = a.in_out','left');
        $this->datatables->join('ref_activities c','c.id = a.activity_id','left');

        // add this line for join
        //$this->datatables->join('table2', 'accountings.field = table2.field');

        // Remove the comment to add filtering data
        // if ($contract_id !== NULL)
        // {
        //     $this->datatables->where('[a.]contract_id', $contract_id);
        // }        
        
        $this->datatables->add_column('action', anchor(site_url('admin/accounting/read/$1'),'<i class=\'fa fa-eye\'></i>')."&nbsp&nbsp".anchor(site_url('admin/accounting/update/$1'),'<i class=\'fa fa-pencil-square-o\'></i>'), 'id');
        return $this->datatables->generate();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id', $q);
	$this->db->or_like('in_out', $q);
	$this->db->or_like('activity_id', $q);
	$this->db->or_like('activity_date', $q);
	$this->db->or_like('amount', $q);
	$this->db->or_like('people', $q);
	$this->db->or_like('description', $q);
	$this->db->or_like('status_data', $q);
	$this->db->or_like('create_userid', $q);
	$this->db->or_like('update_userid', $q);
	$this->db->or_like('create_time', $q);
	$this->db->or_like('update_time', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id', $q);
	$this->db->or_like('in_out', $q);
	$this->db->or_like('activity_id', $q);
	$this->db->or_like('activity_date', $q);
	$this->db->or_like('amount', $q);
	$this->db->or_like('people', $q);
	$this->db->or_like('description', $q);
	$this->db->or_like('status_data', $q);
	$this->db->or_like('create_userid', $q);
	$this->db->or_like('update_userid', $q);
	$this->db->or_like('create_time', $q);
	$this->db->or_like('update_time', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

}

/* End of file Accounting_model.php */
/* Location: ./application/models/Accounting_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Custom Codeigniter CRUD Generator 2020-02-11 22:02:32 */