<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Account_model extends MY_Model
{

    public $table = 'accounts';
    public $id = 'id';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // datatables
    function json($contract_id = NULL) {
        $this->datatables->select('a.id,a.parent_id,a.ref_charttype,b.type_name,a.level_num,a.chart_num,a.chart_name,a.status_data,a.create_userid,a.update_userid,a.create_time,a.update_time');
        $this->datatables->from('accounts a');
        $this->datatables->join('ref_charttypes b','b.id = a.ref_charttype');
        $this->db->order_by('a.id','ASC');

        // add this line for join
        //$this->datatables->join('table2', 'accounts.field = table2.field');

        // Remove the comment to add filtering data
        // if ($contract_id !== NULL)
        // {
        //     $this->datatables->where('[a.]contract_id', $contract_id);
        // }        
        
        $this->datatables->add_column('action', anchor(site_url('admin/account/read/$1'),'<i class=\'fa fa-eye\'></i>')."&nbsp&nbsp".anchor(site_url('admin/account/update/$1'),'<i class=\'fa fa-pencil-square-o\'></i>')."&nbsp&nbsp".anchor(site_url('admin/account/delete/$1'),'<i class=\'fa fa-trash-o\'></i>','onclick="javasciprt: return confirm(\'Anda yakin ?\')"'), 'id');
        return $this->datatables->generate();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id', $q);
	$this->db->or_like('parent_id', $q);
	$this->db->or_like('ref_charttype', $q);
	$this->db->or_like('level_num', $q);
	$this->db->or_like('chart_name', $q);
	$this->db->or_like('status_data', $q);
	$this->db->or_like('create_userid', $q);
	$this->db->or_like('update_userid', $q);
	$this->db->or_like('create_time', $q);
	$this->db->or_like('update_time', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id', $q);
	$this->db->or_like('parent_id', $q);
	$this->db->or_like('ref_charttype', $q);
	$this->db->or_like('level_num', $q);
	$this->db->or_like('chart_name', $q);
	$this->db->or_like('status_data', $q);
	$this->db->or_like('create_userid', $q);
	$this->db->or_like('update_userid', $q);
	$this->db->or_like('create_time', $q);
	$this->db->or_like('update_time', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    function get_level_parent($id = 0){
        if ($id!=0)
        {
            $this->db->select('level_num');
            $this->db->where('id',$id);
            $result = $this->db->get('accounts')->row();
            return $result->level_num + 1;
        } else {
            return 0;
        }
    }

    function type_chart_list()
    {
        $this->db->from('ref_charttypes');
        $this->db->order_by('id','asc');
        $result = $this->db->get();

        $return = array('');

        if ($result->num_rows() > 0)
        {
            $return[0] = '-- Pilih Tipe Rekening --';
            foreach ($result->result_array() as $row) {
                $return[$row['id']] = $row['type_name'];
            }
        } else {
            $return[0] = '-- Pilih Tipe Rekening --';
        }

        return $return;     
    }  

    function account_list()
    {
        $this->db->from('accounts');
        $this->db->order_by('id','asc');
        $result = $this->db->get();

        $return = array('');

        if ($result->num_rows() > 0)
        {
            $return[0] = '-- Pilih Rekening Induk --';
            foreach ($result->result_array() as $row) {
                $return[$row['id']] = $row['chart_name'];
            }
        } else {
            $return[0] = '-- Pilih Rekening Induk --';
        }

        return $return;     
    }  

    function get_acc_num($id)
    {
        if ($id!=0)
        {
            $this->db->select('chart_num');
            $this->db->where('id',$id);
            return $this->db->get('accounts')->row();
        } else {
            return 0;
        }
    }
}

/* End of file Account_model.php */
/* Location: ./application/models/Account_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Custom Codeigniter CRUD Generator 2019-02-07 16:09:28 */