<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Pastor_model extends MY_Model
{

    public $table = 'pastors';
    public $id = 'id';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // datatables
    // function json($contract_id = NULL) {
    function json($val) {
        $this->datatables->select('a.id,remarks,a.rank_id,b.rank_name,a.status_data,a.create_userid,a.update_userid,a.create_time,a.update_time');
        $this->datatables->from('pastors a');
        $this->datatables->join('ref_ranks b','b.id = a.rank_id','left');


        // add this line for join
        //$this->datatables->join('table2', 'pastors.field = table2.field');

        // Remove the comment to add filtering data
        // if ($contract_id !== NULL)
        // {
        //     $this->datatables->where('[a.]contract_id', $contract_id);
        // }        

        // print_r($usergroup);

        $col_read = anchor(site_url('admin/pastor/read/$1'),'<i class=\'fa fa-eye\'></i>');
        $col_update = anchor(site_url('admin/pastor/update/$1'),'<i class=\'fa fa-pencil-square-o\'></i>');
        $col_delete = anchor(site_url('admin/pastor/delete/$1'),'<i class=\'fa fa-trash-o\'></i>','onclick="javasciprt: return confirm(\'Anda yakin ?\')"');


        if ($val === 'webmaster' || $val === 'admin') {
            $this->datatables->add_column('action', $col_read."&nbsp&nbsp".$col_update."&nbsp&nbsp".$col_delete, 'id');
        } else {
            $this->datatables->add_column('action', $col_read."&nbsp&nbsp&nbsp&nbsp".$col_update, 'id');
        }

        return $this->datatables->generate();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where('a.'.$this->id, $id);
        $this->db->select('a.id,a.remarks,a.rank_id,b.rank_name,a.status_data');
        $this->db->join('ref_ranks b','b.id = a.rank_id','left');
        return $this->db->get($this->table.' a')->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id', $q);
	$this->db->or_like('remarks', $q);
	$this->db->or_like('status_data', $q);
	$this->db->or_like('create_userid', $q);
	$this->db->or_like('update_userid', $q);
	$this->db->or_like('create_time', $q);
	$this->db->or_like('update_time', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id', $q);
	$this->db->or_like('remarks', $q);
	$this->db->or_like('status_data', $q);
	$this->db->or_like('create_userid', $q);
	$this->db->or_like('update_userid', $q);
	$this->db->or_like('create_time', $q);
	$this->db->or_like('update_time', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

}

/* End of file Pastor_model.php */
/* Location: ./application/models/Pastor_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Custom Codeigniter CRUD Generator 2018-08-03 11:12:40 */