<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Relationship_model extends MY_Model
{

    public $table = 'relationships';
    public $id = 'id';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // datatables
    function json($contract_id = NULL) {
        $this->datatables->select('id,family_id,individu_1_id,individu_2_id,relationship_type_id,ind_1_role_id,ind_2_role_id,date_relationship_start,date_relationship_end,relationship_place,remarks,status_data,create_userid,update_userid,create_time,update_time');
        $this->datatables->from('relationships');

        // add this line for join
        //$this->datatables->join('table2', 'relationships.field = table2.field');

        // Remove the comment to add filtering data
        // if ($contract_id !== NULL)
        // {
        //     $this->datatables->where('[a.]contract_id', $contract_id);
        // }        
        
        $this->datatables->add_column('action', anchor(site_url('admin/relationship/read/$1'),'<i class=\'fa fa-eye\'></i>')."&nbsp&nbsp".anchor(site_url('admin/relationship/update/$1'),'<i class=\'fa fa-pencil-square-o\'></i>')."&nbsp&nbsp".anchor(site_url('admin/relationship/delete/$1'),'<i class=\'fa fa-trash-o\'></i>','onclick="javasciprt: return confirm(\'Apakah anda yakin untuk menghapus data ini ?\')"'), 'id');
        return $this->datatables->generate();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id', $q);
	$this->db->or_like('family_id', $q);
	$this->db->or_like('individu_1_id', $q);
	$this->db->or_like('individu_2_id', $q);
	$this->db->or_like('relationship_type_id', $q);
	$this->db->or_like('ind_1_role_id', $q);
	$this->db->or_like('ind_2_role_id', $q);
	$this->db->or_like('date_relationship_start', $q);
	$this->db->or_like('date_relationship_end', $q);
	$this->db->or_like('relationship_place', $q);
	$this->db->or_like('remarks', $q);
	$this->db->or_like('status_data', $q);
	$this->db->or_like('create_userid', $q);
	$this->db->or_like('update_userid', $q);
	$this->db->or_like('create_time', $q);
	$this->db->or_like('update_time', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id', $q);
	$this->db->or_like('family_id', $q);
	$this->db->or_like('individu_1_id', $q);
	$this->db->or_like('individu_2_id', $q);
	$this->db->or_like('relationship_type_id', $q);
	$this->db->or_like('ind_1_role_id', $q);
	$this->db->or_like('ind_2_role_id', $q);
	$this->db->or_like('date_relationship_start', $q);
	$this->db->or_like('date_relationship_end', $q);
	$this->db->or_like('relationship_place', $q);
	$this->db->or_like('remarks', $q);
	$this->db->or_like('status_data', $q);
	$this->db->or_like('create_userid', $q);
	$this->db->or_like('update_userid', $q);
	$this->db->or_like('create_time', $q);
	$this->db->or_like('update_time', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

}

/* End of file Relationship_model.php */
/* Location: ./application/models/Relationship_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Custom Codeigniter CRUD Generator 2019-10-04 05:24:55 */