<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Vw_accreport_model extends MY_Model
{

    public $table = 'vw_accreports';
    public $id = '';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // datatables
    function json($contract_id = NULL) {
        $this->datatables->select('activity_date,yearnum,monthnum,weeknum,activity_name,amount,people');
        $this->datatables->from('vw_accreports');

        // add this line for join
        //$this->datatables->join('table2', 'vw_accreports.field = table2.field');

        // Remove the comment to add filtering data
        // if ($contract_id !== NULL)
        // {
        //     $this->datatables->where('[a.]contract_id', $contract_id);
        // }        
        
        $this->datatables->add_column('action', anchor(site_url('admin/vw_accreport/read/$1'),'<i class=\'fa fa-eye\'></i>')."&nbsp&nbsp".anchor(site_url('admin/vw_accreport/update/$1'),'<i class=\'fa fa-pencil-square-o\'></i>')."&nbsp&nbsp".anchor(site_url('admin/vw_accreport/delete/$1'),'<i class=\'fa fa-trash-o\'></i>','onclick="javasciprt: return confirm(\'Apakah anda yakin untuk menghapus data ini ?\')"'), '');
        return $this->datatables->generate();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('', $q);
	$this->db->or_like('activity_date', $q);
	$this->db->or_like('yearnum', $q);
	$this->db->or_like('monthnum', $q);
	$this->db->or_like('weeknum', $q);
	$this->db->or_like('activity_name', $q);
	$this->db->or_like('amount', $q);
	$this->db->or_like('people', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('', $q);
	$this->db->or_like('activity_date', $q);
	$this->db->or_like('yearnum', $q);
	$this->db->or_like('monthnum', $q);
	$this->db->or_like('weeknum', $q);
	$this->db->or_like('activity_name', $q);
	$this->db->or_like('amount', $q);
	$this->db->or_like('people', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

}

/* End of file Vw_accreport_model.php */
/* Location: ./application/models/Vw_accreport_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Custom Codeigniter CRUD Generator 2020-03-02 07:08:18 */